/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pompa.insulina;

public class App {

    public static void main(String[] args) {

        Sistema sis = new Sistema();
        sis.lanciaSensore();
        sis.lanciaControllore();

    }
}
