/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pompa.insulina;

public class Controllore {

    //attributi
    private double zuccheri1;
    private double zuccheri0;
    private int dosePrecedente;

    //costruttore
    public Controllore(){
        this.zuccheri1 = 0.0;
        this.zuccheri0 = 0.0;
        this.dosePrecedente = 0;
    }

    //metodi
    synchronized public double getZuccheri(){
        return zuccheri1;
    }

    synchronized public void setDosePrecedente(int dose){
        dosePrecedente = dose;
    }

    synchronized public void resetZuccheri(){
        zuccheri0 = 0;
        zuccheri1 = 0;
    }

    synchronized public void calcolaZuccheri(double condElettrica){
        zuccheri0 = zuccheri1;
        zuccheri1 = condElettrica/10.0;
    }

    synchronized public int calcolaDose(){

        //controllo se il tasso è in salita tra 5.0 e 7.0
        if (zuccheri1 > 5 && zuccheri1 < 7 && zuccheri1 > zuccheri0){
            //Somministro 1 o 2 dosi (se posso)
            return Math.min( (5 - dosePrecedente), ((int) zuccheri1 - 4) );
        }
        if (zuccheri1 > 7){
            //massima dose somministrabile
            return 5 - dosePrecedente;
        }
        //in tutti gli altri casi
        return 0;
    }

    //metodi per il test
    public double getZuccheri0(){return zuccheri0;}
    public int getDosePrecedente(){return dosePrecedente;}
    public void setZuccheri1(double z){zuccheri1 = z;}
    public void setZuccheri0(double z){zuccheri0 = z;}
}
