/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pompa.insulina;

public class Serbatoio {

    //attributo
    private int dosiResidue;

    //costruttore
    public Serbatoio(){
        this.dosiResidue = 20;
    }

    //metodi
    public void sottraiDosi(int impulsi){
        //solo se posso
        if (impulsi <= dosiResidue){
            dosiResidue -= impulsi;
        }
        else{
            throw new ArithmeticException();
        }
    }

    public int getDosi(){
        return dosiResidue;
    }

    public void riempi() {
        dosiResidue = 20;
    }
}
