/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pompa.insulina;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class DisplayTest {

    @Test public void testConstructor() {

        Sistema.test_mode = true;
        Display display = new Display();

        assertEquals("Zuccheri a 0", 0, display.getZuccheri(), 0.0);
        assertEquals("Serbatoio pieno", 20, display.getDosiResidue());
        assertTrue("Flags inizializzati a True",display.getAllarmeSerbatoio() && display.getAllarmeZuccheri());

    }

    @Test public void testAggiungiRegistrazione() throws InterruptedException {

        Sistema.test_mode = true;
        Display display = new Display();

        for (int i = 0; i < 20; i++){
            display.aggiungiRegistrazione("test");
            assertEquals("Fino a 20 registrazioni", display.getRegistrazioni().size(), i + 1);
            Thread.sleep(1000);
        }

        for (int i = 0; i < 10; i++){
            display.aggiungiRegistrazione("test");
            assertEquals("non più di 20 registrazioni contemporanee", 20, display.getRegistrazioni().size());
            Thread.sleep(1000);
        }

    }
}
