/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pompa.insulina;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class SensoreTest {

    @Test public void testConstructor() {

        Sensore s = new Sensore();
        assertTrue("attributi inizializzati a 0", s.getGenerazioni() == 0 && s.getUltimaDose() == 0);

        for (int i = 0; i < 1000; i++){
            Sensore sensore = new Sensore();
            assertTrue("Valore casuale tra 30 e 70",sensore.getCondElettrica() >= 30 && sensore.getCondElettrica() <= 70);
        }
    }

    @Test public void testgeneraValore(){

        Sensore sensore = new Sensore();

        sensore.generaValore();
        assertEquals("é passata una generazione", 1, sensore.getGenerazioni());

        // La cosa fondamentale è che sia sempre un numero tra 0 e 100
        // Il resto è sempre pseudo-casuale, visto che c'è un 2% di prob.
        for (int i = 0; i < 1000; i++){

            //ogni 5 volte somministro una nuova dose casualmente
            if (i % 5 == 0){
                sensore.setUltimaDose((int)(Math.random()*5));
                assertEquals(0, sensore.getGenerazioni());
            }

            sensore.generaValore();
            assertTrue("Valore tra 0 e 100", sensore.getCondElettrica() >= 0 && sensore.getCondElettrica() <= 100);
        }

    }

}
