/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pompa.insulina;

import org.junit.Test;
import static org.junit.Assert.*;

public class SerbatoioTest {

    @Test public void testConstructor() {
        Serbatoio serbatoio = new Serbatoio();
        assertEquals("Il serbatoio creato è pieno", 20, serbatoio.getDosi());
    }

    @Test public void testSottraiDosi(){
        Serbatoio serbatoio = new Serbatoio();

        serbatoio.sottraiDosi(15);
        assertEquals("5 dosi residue", 5, serbatoio.getDosi());

        try{
            serbatoio.sottraiDosi(6);
        }
        catch(ArithmeticException e){
            assertTrue("non posso sottrarre più dosi di quelle disponibili",true);
        }
    }

    @Test public void testRiempi(){

        Serbatoio serbatoio = new Serbatoio();

        serbatoio.sottraiDosi(15);
        serbatoio.riempi();
        assertEquals("Serbatoio Pieno", 20, serbatoio.getDosi());
    }
}
